### ISSUE TITLE
Make dark mode more accessible 

### ISSUE THREAD

**Issue by YuriCodes** [ElvinPero/PriceTemplate#121]
Making the dividing lines and other visual elements will provide the right contrast for accessibility issues for people with low vision.

I can work on this if you'd like. 

example: 

<img width="1259" alt="Screen Shot 2022-10-15 at 10 36 12 AM" src="https://user-images.githubusercontent.com/80093500/195992254-6fe7af0b-a682-4d50-8ad4-f16e1f6df3b1.png">

**Comment by ElvinPero** [comment]
@YuriCodes Sure go ahead. and please do the following changes .
1)contrast
2)button glow 
3)Colors blue is fine please alter red of light mode to be a little pinkish. dont alter dark of red ,dark is fine.
and add a greenish blue color instead of purple 

also for about us rectangle.
4)Put cursor to pointer for dark mode toggle when we over

**Comment by ElvinPero** [comment]
@YuriCodes Any updates?

**Comment by YuriCodes** [comment]
I'll work on it right now, thank u

**Comment by ElvinPero** [comment]
@YuriCodes Go ahead
