### ISSUE TITLE
enhancement of navbar

### ISSUE THREAD

**Issue by aditi10701** [ElvinPero/PriceTemplate#53]
A similar navbar can be put to give better user UI experience.
Kindly assign me this issue. I want to work on it.
![image](https://user-images.githubusercontent.com/98349669/194926835-6e3bf967-14b1-442e-a467-eeafa638095d.png)

**Comment by Siddhesh172004** [comment]
![navbar1](https://user-images.githubusercontent.com/84581657/194931464-364a923a-eb4f-4ff6-9360-970b0fb97521.JPG)

When we click the search bar this pops up :- 

![navbar2](https://user-images.githubusercontent.com/84581657/194931588-fe5e2268-2086-48dc-bfa2-74a736a1d0b7.JPG)


We can add the toggle button of dark mode  and can put the center menu link to the right side similar to your design. 

As mentioned in the above photos I will change the color of navbar  so that it can be best combination for your website .  I would love to enhance the navbar.  If you don't like about design navbar so I have other options too. Kindly assign this issue to as soon as possible.

Above navbar is from my own website : - http://siddhesh1720045.pythonanywhere.com/mens/

**Comment by ElvinPero** [comment]
@Siddhesh172004 go for it and please make appropriate fields in nav
